apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-django-app
  namespace: my-namespace
  labels:
    app: my-django-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-django-app
  template:
    metadata:
      labels:
        app: my-django-app
    spec:
      containers:
        - name: my-django-app
          image: vireshsolanki/myproject:1.0
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: 'terraform-20231008155010428500000001.cktmkdbirt3n.ap-south-1.rds.amazonaws.com'
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: mydb
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
