version: "3.8"
services:
  app: 
   build: .
   volumes:
    - .:/website
   ports:
    - 8000:8000
   image: app:shoeshades
   container_name: website
   command: python manage.py runserver 0.0.0.0:8000
 

