apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate-job
  namespace: my-namespace
spec:
  template:
    spec:
      containers:
      - name: migrate-container
        image: vireshsolanki/myproject:1.0  # Use the same image as your Django application
        command: ["python", "manage.py", "migrate"]
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "shoeshade.settings"
      restartPolicy: Never
