apiVersion: v1
kind: Service
metadata:
  name: my-django-app-service
  namespace: my-namespace
spec:
  selector:
    app: my-django-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
    