name: website deployment
on:
  push:
    branches:
    - master
jobs:
  deploy:
    name: deploy to staging
    runs-on: self-hosted
    strategy:
     max-parallel: 4
     matrix:
       python-version: [3.9]
     
    steps:
    - name: Cache Python 3.9.7 installation
      uses: actions/cache@v3
      with:
          path: /tmp/python-cache
          key: ${{ runner.os }}-python-${{ inputs.python-version }}
          restore-keys: |
            ${{ runner.os }}-python-
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v3.0.0
    - name: docker login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
      #run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: build and push
      run: |
        docker build -t vireshsolanki/myproject:1.0 .
        docker push vireshsolanki/myproject:1.0
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        
    - name: Upgrade pip
      run: python3 -m pip install --upgrade pip
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
         python-version: ${{matrix.python-version}}
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: aws cli
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY}}
        aws-secret-access-key: ${{secrets.SECRET_KEY}}
        aws-region: ap-south-1
    - name: authenticate eks
      run: aws eks --region ap-south-1 update-kubeconfig --name eks
    - name: create namespace
      run: kubectl create namespace my-namespace
    - name: deploy to eks
      run: kubectl apply -f deployment.yml
    - name: run database migrations
      run: |
        kubectl exec -it deployment/my-django-app -n my-namespace -- python manage.py migrate
      env:
        DJANGO_SETTINGS_MODULE: "shoeshade.settings"
      
        
   
